os: linux
dist: xenial
language: python


# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
  - 3.7
  - 3.8

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION="1.16"
        - ASDF_GIT="git+https://github.com/spacetelescope/asdf.git#egg=asdf"
        - ASTROPY_GIT="git+https://github.com/astropy/astropy.git#egg=astropy"
        - PIP_DEPENDENCIES=.[test]
        - TEST_COMMAND=pytest

jobs:
    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Do a security check
        - env:
            TEST_COMMAND="bandit -r gwcs -c .bandit.yaml"
            PIP_DEPENDENCIES=bandit

        # Do a coverage test.
        - python: "3.7"
          env:
            TEST_COMMAND="pytest --cov-config=gwcs/tests/coveragerc --cov=gwcs"
            PIP_DEPENDENCIES=".[test] coveralls pytest-cov"

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: "3.8"
          env: 
            PIP_DEPENDENCIES=".[docs]"
            TEST_COMMAND="make --directory=docs html"
          addons:
            apt:
              packages:
                - graphviz
                - texlive-latex-extra
                - dvipng

        - python: "3.6"
          env:
            NUMPY_VERSION="1.17"

        - python: "3.7"
          env:
            NUMPY_VERSION="1.17"

        - python: "3.8"
          env:
            NUMPY_VERSION="1.17"

        # Do a PEP8 test with flake8
        - python: "3.8"
          env:
            TEST_COMMAND="flake8 gwcs --count"
            PIP_DEPENDENCIES=flake8

        - python: "3.8"
          env:
            PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"


    allow_failures:
        - python: "3.8"
          env:
            PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

install:
  - pip install numpy~=$NUMPY_VERSION
  - pip install $PIP_DEPENDENCIES


script:
    - $TEST_COMMAND

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $TEST_COMMAND == *--cov* ]]; then
          coveralls --rcfile='gwcs/tests/coveragerc';
      fi
